### ISSUE TITLE
virus

### ISSUE THREAD

**Issue by Daanthe** [SHREK-TM/Shrek-Tools#1]
stupid ass }

**Comment by SHREK-TM** [comment]
HI can u give more information, do you have a probleme with your defendre ?

**Comment by SHREK-TM** [comment]
no aswer

**Comment by Daanthe** [comment]
Dumb ass nigga stop tryna hack  kids bruh
________________________________

**Comment by SHREK-TM** [comment]
i know who u are and what u trying to do little d*mbe
keep ur comment for ur self, Bye.

**Comment by Daanthe** [comment]
Who am I nigga

Op za 27 jul 2024 om 00:33 schreef SHREK™ ***@***.***>

**Comment by SHREK-TM** [comment]
aziz thats remembre u something ?

**Comment by Daanthe** [comment]
Who tf is aziz nigga

Op za 27 jul 2024 om 18:13 schreef SHREK™ ***@***.***>
